jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        ruby: [ '2.5', '2.6' ]
    name: Ruby ${{ matrix.ruby }} sample
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
                 gem install wayback_machine_downloader
                 wayback_machine_downloader http://chemax.ru
      - uses: actions/upload-artifact@v4
         with:
           name: Chemax.ru
           path: ./websites/ 