jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby: [ '2.5' ]
    name: Ruby ${{ matrix.ruby }} sample
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
                 gem install wayback_machine_downloader
                 wayback_machine_downloader http://chemax.ru
